name: CI

on:
push:
  branches: [main]

pull_request:
  branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - user: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests (HEADLESS) #to run headless
        run: npm run wdio

      - name: generate Allure report
        run: npm run report:generate

      - name: Deploy Allure report to Github Pages
        user: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          publish_dir: ./allure-report
          publish_branch: gh-pages
